# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/R9000X/Desktop/jiekou_lab/lab2/RVfpga_Soc_uart/RVfpga_Soc.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_xbar_0/swerv_soc_xbar_0.xci
# IP: The module: 'swerv_soc_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/R9000X/Desktop/jiekou_lab/lab2/RVfpga_Soc_uart/RVfpga_Soc.gen/sources_1/bd/swerv_soc/ip/swerv_soc_xbar_0/swerv_soc_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'swerv_soc_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/R9000X/Desktop/jiekou_lab/lab2/RVfpga_Soc_uart/RVfpga_Soc.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_xbar_0/swerv_soc_xbar_0.xci
# IP: The module: 'swerv_soc_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/R9000X/Desktop/jiekou_lab/lab2/RVfpga_Soc_uart/RVfpga_Soc.gen/sources_1/bd/swerv_soc/ip/swerv_soc_xbar_0/swerv_soc_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'swerv_soc_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
